version: "3.8"
services:
  gateway:
    image: mohsenmoeini/api-gateway:0.1
    ports:
      - "8090:8090"
    restart: on-failure
    depends_on:
      - keycloak
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: expenses
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://expenses:8082
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/api/expenses/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: threshold
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://expenses:8082
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/api/thresholds/**

  expenses:
    image: mohsenmoeini/expense-tracker:0.1
    depends_on:
      - keycloak
    ports:
      - "8082:8082"
    restart: on-failure
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expenses_db
