server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: expenses-service
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/expenses_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: TRACE
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

# Swagger UI configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: gateway-resource-server
      client-secret: bV7cKkhM0LYQ6eNGSl0BKzPTPMx2ACR7
      use-pkce-with-authorization-code-grant: false
      use-basic-authentication-with-access-code-grant: false
      scope-separator: " "
      scopes:
        - openid
        - profile
        - email
      token-url: http://localhost:8080/realms/master/protocol/openid-connect/token
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-security-scheme-name: keycloak_oauth
