server:
  port: 8090
  address: 0.0.0.0

spring:
  application:
    name: expenses-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: expenses
          uri: http://localhost:8082
          predicates:
            - Path=/api/expenses/**

        - id: threshold
          uri: http://localhost:8082
          predicates:
            - Path=/api/thresholds/**

logging:
  level:
    org.springframework.cloud.gateway: trace