server:
  port: 8090

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
            maxAge: 3600
      routes:
        - id: expenses-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/expenses/**, /api/thresholds/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG